language: node_js
node_js:
  - "4.1"

services: mongodb
sudo: required
dist: trusty

before_script:
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - npm install -g gulp
  - rvm 2.2.3
  - gem install scss_lint

script:
  - gulp
