language: node_js
node_js:
  - "4.1"

services:
  - mongodb

#sudo: required
#dist: trusty

before_install:
#  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
#  - echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
#  - sudo apt-get update
#  - sudo apt-get install -y mongodb-org=3.0.5 mongodb-org-server=3.0.5 mongodb-org-shell=3.0.5 mongodb-org-mongos=3.0.5 mongodb-org-tools=3.0.5

before_script:
#  - sudo service mongod status

script:
  - mongo genotet < mongo_init.js


